server:
  port: 8091
  compression:
    enabled: true
    min-response-size: 512B # 起步压缩大小(即大于512B才会压缩)
  servlet:
    session:
      timeout: 60
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 20MB
      # 最大支持请求大小
      max-request-size: 30MB
  tomcat:
    connection-timeout: 60


spring:
  datasource:
    druid:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${DB_USER_NAME:traveldesigner}
      password: ${DB_PASSWORD:designtraveller}
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）



xzWeather:
  weatherCode: Sq1q8PfzspO4-LWd_

waCOVID:
  appId: 7546
  COVIDCode: 92f9473ba2769523d5c798df45a96dfb
